### PR TITLE
Forman master dev 3 login

### PR DESCRIPTION
**Pull request by forman**
* added app mode selector page to switch between stand-alone and SaaS mode
* added login screen for Cate SaaS mode
* some minor fixes

### CODE REVIEW

**Review by dzelge — COMMENTED** [review]
We should probably discuss the login and how to implement CateHub a bit more. I am not entirely sure whether a login dialog in cate desktop makes sense. It is at least disputable if we followed the JupyterHub architectural design. Analogously speaking, cate desktop is like a Jupyter Lab and catehub is like JupyterHub. In that design the Login Dialog is provided by JupyterHub.

**Comment by forman** [comment]
> We should probably discuss the login and how to implement CateHub a bit more. 

Sure. Don't forget, this branch is still demo code.

> I am not entirely sure whether a login dialog in cate desktop makes sense. 

Where else?

**Comment by dzelge** [comment]
As I pointed out: If we used the design of JupyterHub, we would use the 'Hub'. In JupyterHub the Hub provides admin and login functionality. If we used the JupyterHub design.

**Comment by forman** [comment]
> As I pointed out: If we used the design of JupyterHub, we would use the 'Hub'. In JupyterHub the Hub provides admin and login functionality. If we used the JupyterHub design.

I don't see why login cannot or shouldn't be build into the Cate Desktop UI. CateHub (JupyterHub like) is a backend. In the end, user open Cate Desktop app or Cate Desktop in a browser via a URL and they are asked to login, if they wish to use CateHub. If so, Cate Desktop UI code uses any authorisation endpoint. 

Anyway, this is still demo code, and login is not yet implemented at all.

**Review by dzelge — APPROVED** [review]

**Review by SabineEmbacher — APPROVED** [review]
It looks okay to me. But it's much more code than just log in.

**Pull request merged**
